// <auto-generated />
namespace Cik.MagazineWeb.EntityFrameworkProvider.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedUserApplication20130514 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedUserApplication20130514));
        
        string IMigrationMetadata.Id
        {
            get { return "201305140453482_AddedUserApplication20130514"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
