// <auto-generated />
namespace Cik.MagazineWeb.EntityFrameworkProvider.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RemoveSomeRequireOnUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemoveSomeRequireOnUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201305141037311_RemoveSomeRequireOnUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
