// <auto-generated />
namespace Cik.MagazineWeb.EntityFrameworkProvider.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RemovePasswordRequireOnUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemovePasswordRequireOnUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201305141053146_RemovePasswordRequireOnUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
